### ISSUE TITLE
Working with nodejs from another container

### ISSUE THREAD

**Issue by gabiudrescu** [notFloran/mjml-bundle#16]
first of all, let me congratulate you, the maintainer of this bundle, for the effort you put into creating this. it's awesome and makes the life of a Symfony user very easy when it comes to handling emails.

my question for you is how can I use this bundle in a Docker environment where nodejs is not installed in the same container where is PHP-FPM running?

from what I've seen, this bundle relies on having the mjml binary available and runnable in the same environment as PHP.

**Comment by notFloran** [comment]
Hi @gabiudrescu 

> first of all, let me congratulate you, the maintainer of this bundle, for the effort you put into creating this. it's awesome and makes the life of a Symfony user very easy when it comes to handling emails.

Thanks !!

> my question for you is how can I use this bundle in a Docker environment where nodejs is not installed in the same container where is PHP-FPM running?
from what I've seen, this bundle relies on having the mjml binary available and runnable in the same environment as PHP.

For the moment no solution :(

I'm working on a new major version (#17) to allow multiple backend to render the MJML content:

* binary
* the official API: https://mjml.io/api 
* maybe some others solutions like https://github.com/shyim/mjml-server or 
tcpserver.js of https://github.com/liminspace/django-mjml

**Comment by gabiudrescu** [comment]
well.. this sounds like a pretty good starting point of using MJML outside the main docker container that does not contain nodejs. 

I'll follow these issues to give you a helping hand on testing this.

**Comment by notFloran** [comment]
The bundle now includes a "Renderer" system that allows you to manage it yourself (API ou other solutions like https://github.com/notFloran/mjml-bundle/issues/16#issuecomment-416714369). 

See https://github.com/notFloran/mjml-bundle#custom

**Comment by gabiudrescu** [comment]
Congratulations! Glad to hear that from you
