### ISSUE TITLE
Binary to mjml

### ISSUE THREAD

**Issue by TomPradat** [notFloran/mjml-bundle#3]
Hi, how can i get a binary for mjml ? Or is the config bin supposed to indicate the node binary ?

**Comment by notFloran** [comment]
Hi @TomPradat,

You need to install mjml with npm/yarn and set the config like this:

```
mjml:
    bin: "%kernel.root_dir%/../node_modules/.bin/mjml"
```

**Comment by TomPradat** [comment]
Thank you for your fast answer.

Ok that's what i though. I was hoping maybe there was a solution without using npm because i'm hosting the website on ovh that does not have npm available.

**Comment by notFloran** [comment]
Sorry :(

In the future I will try to include a mode where the bundle use the [API](https://mjml.io/api) instead of the binary.

**Comment by notFloran** [comment]
Feature still not developed, sorry.

See #4
