### ISSUE TITLE
mjml command -i?

### ISSUE THREAD

**Issue by fogx** [notFloran/mjml-bundle#63]
Hi, im trying to get the plugin to run on my system. I noticed, that the plugin runs the command `mjml -i -s --...`
i can't find the command -i in the mjml documentation, and using it manually will throw an exception. Can you explain what it is used for?
It is from the binary renderer code here:
```
    public function render(string $mjmlContent): string
    {
        $version = $this->getMjmlVersion();

        // Tab arguments
        $arguments = [
            $this->bin,
            '-i',
            '-s',
        ];

```

**Comment by notFloran** [comment]
Hi,

The `-i` is used to compile from input stream, see the followinf screenshot:

<img width="580" alt="CleanShot 2020-06-07 at 19 31 08@2x" src="https://user-images.githubusercontent.com/523981/83975712-7749ca80-a8f5-11ea-8bd7-2ccd9211d096.png">

Which version are you using?
