### ISSUE TITLE
a href -  Element a doesn't exist or is not registered

### ISSUE THREAD

**Issue by mpawlak96** [notFloran/mjml-bundle#75]
Hello!

Im trying to use mjml-bundle for symfony (5.1). Installation works OK but in template i have a `a href` tag. I cant render this template (mjml on PC is rendering template correct) because im getting error: 

```
Error Output:
================
nullError: ValidationError:
Line 29 of XXXXXXX/public (a) — Element a doesn't exist or is not registered
```

Is there any option to fix this ?

**Comment by notFloran** [comment]
Hi !

I see you ask for help in the MJML repo (https://github.com/mjmlio/mjml/issues/2304), Is that good ?
