### ISSUE TITLE
Prepare for Symfony 6

### ISSUE THREAD

**Issue by notFloran** [notFloran/mjml-bundle#76]
https://symfony.com/blog/preparing-your-apps-and-bundles-for-symfony-6

https://wouterj.nl/2021/09/symfony-6-native-typing

**Comment by maczuk** [comment]
Hi @notFloran! First of all, I would like to thank you for this bundle! It helped me a lot in the recent projects.

I wanted to ask when you plan to release support for sf6? I saw that `dev-main` branch already has support for v6 so for now I've used this one but it will be great to use stable version ;)

Thank you,
Maciek

**Comment by notFloran** [comment]
Hi @maczuk !

I will look to make a new release before the end of the week

**Comment by notFloran** [comment]
Hi @maczuk !

I just made a new release.

**Comment by maczuk** [comment]
Hi @notFloran! Thank you so much!

Have a great week!
